### PR TITLE
fix: keep parent in strict mode

### PR DESCRIPTION
**Pull request by tmkx**
fix for `keepParent: false`, portal container should be attached to parent.

```tsx
<Tooltip
  title="Antd Tooltip"
  destroyTooltipOnHide={{ keepParent: false }}
>
  <span>Antd Tooltip</span>
</Tooltip>
```

### CODE REVIEW

**Comment by zombieJ** [comment]
加一个测试用例？

**Comment by tmkx** [comment]
> 加一个测试用例？

这个 repo 还是 enzyme，不好加...

**Comment by zombieJ** [comment]
帮忙转一波~~？

**Comment by tmkx** [comment]
> 帮忙转一波~~？

https://github.com/react-component/trigger/pull/296

**Comment by tmkx** [comment]
> 加一个测试用例？

done

**Comment by zombieJ** [comment]
`+ rc-trigger@5.2.16`

**Pull request merged**
