### PR TITLE
5.2.4

### PR DESCRIPTION
**Pull request by dimpu**
Version update.

### CODE REVIEW

**Comment by dimpu** [comment]
@zombieJ @yiminghe

**Comment by zombieJ** [comment]
Thanks for PR.

But rc component use `np` to manage version. It will auto increase in next release.

**Comment by dimpu** [comment]
I see thanks @zombieJ . What I know what's the time line for next release please?

**Comment by zombieJ** [comment]
`rc-trigger@5.2.4`

**Pull request closed without merging**
