### PR TITLE
fix document and window in multi frame context

### PR DESCRIPTION
**Pull request by sanyatuning**

### CODE REVIEW

**Comment by sanyatuning** [comment]
@zombieJ can you review/ merge this?

**Comment by zombieJ** [comment]
Hi, what's the problem with origin `getDocument`?

**Comment by sanyatuning** [comment]
It is pointed to the main window's document, but we use it inside an iframe
so it should be pointed to the document of the iframe

**Comment by zombieJ** [comment]
@kuitos what's your usage of popup in qiankun?

**Comment by sanyatuning** [comment]
@kuitos yes

**Pull request closed without merging**
