### PR TITLE
fix: prevent from creating multi portals again

### PR DESCRIPTION
**Pull request by zombieJ**
Reverts react-component/trigger#293

### CODE REVIEW

**Comment by zombieJ** [comment]
cc @tmkx

**Comment by tmkx** [comment]
LGTM

**Comment by tmkx** [comment]
seems CI failed also after reversion? https://github.com/ant-design/ant-design/runs/5984956967?check_suite_focus=true

**Comment by zombieJ** [comment]
> reversion

Our action use action/cache which cache the node_modules

**Comment by tmkx** [comment]
芭比Q了，我看 antd 好多 PR 原来 ✅ 的现在都 ❌ 了

**Comment by zombieJ** [comment]
原来是国人么………………

少侠直接加钉钉群一起做 v5 不？

https://github.com/ant-design/ant-design/issues/34087#issuecomment-1068988378

**Pull request merged**
