### PR TITLE
fix: ts type

### PR DESCRIPTION
**Pull request by shaodahong**
Ref: https://github.com/react-component/mentions/pull/18

### CODE REVIEW

**Comment by zombieJ** [comment]
OPS. Trigger children should be React.Element. Reverted:
截屏2019-10-17下午9 24 13

**Comment by shaodahong** [comment]
This  `children` if `React.Element` type, Then use `rc-trigger` wrapper component children also is `React.Element`

**Comment by zombieJ** [comment]
Yes. Should be ReactElement since it need children's `props`.

**Comment by shaodahong** [comment]
ok，my fault

**Pull request merged**
